Repository wecode-bootcamp-korea/35-backend-westagram-3, pull requests merged in 2022-07, with the labels that each got.

#1 [조예슬] Mission1: Django 초기 세팅
  students/yeseul/.gitignore
  students/yeseul/manage.py
  students/yeseul/requirements.txt
  students/yeseul/westagram/__init__.py
  students/yeseul/westagram/asgi.py
  students/yeseul/westagram/settings.py
  students/yeseul/westagram/urls.py
  students/yeseul/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [이원재] Mission 1 : Django 초기 세팅
  students/wonjae/.gitignore
  students/wonjae/manage.py
  students/wonjae/requirements.txt
  students/wonjae/westagram/__init__.py
  students/wonjae/westagram/asgi.py
  students/wonjae/westagram/settings.py
  students/wonjae/westagram/urls.py
  students/wonjae/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#6 [조예슬] Mission 2: 모델링
  students/yeseul/users/__init__.py
  students/yeseul/users/admin.py
  students/yeseul/users/apps.py
  students/yeseul/users/migrations/0001_initial.py
  students/yeseul/users/migrations/__init__.py
  students/yeseul/users/models.py
  students/yeseul/users/tests.py
  students/yeseul/users/views.py
  students/yeseul/westagram/settings.py
Labels: 멘토 리뷰 요청

#7 [안상현] Mission1:Django초기 세팅
  students/sanghyun/.gitignore
  students/sanghyun/manage.py
  students/sanghyun/requirements.txt
  students/sanghyun/westagram/__init__.py
  students/sanghyun/westagram/asgi.py
  students/sanghyun/westagram/settings.py
  students/sanghyun/westagram/urls.py
  students/sanghyun/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#5 [이원재] Mission 2 : 모델링
  students/wonjae/users/__init__.py
  students/wonjae/users/admin.py
  students/wonjae/users/apps.py
  students/wonjae/users/migrations/0001_initial.py
  students/wonjae/users/migrations/__init__.py
  students/wonjae/users/models.py
  students/wonjae/users/tests.py
  students/wonjae/users/views.py
  students/wonjae/westagram/settings.py
Labels: 멘토 리뷰 요청

#3 [김민지] Mission 1 : Django 초기 세팅
  students/minji/.gitignore
  students/minji/manage.py
  students/minji/requirements.txt
  students/minji/westargram/__init__.py
  students/minji/westargram/asgi.py
  students/minji/westargram/settings.py
  students/minji/westargram/urls.py
  students/minji/westargram/wsgi.py
Labels: 완료

#8 [안상현] Mission2 : User 모델링
  students/sanghyun/users/__init__.py
  students/sanghyun/users/admin.py
  students/sanghyun/users/apps.py
  students/sanghyun/users/migrations/0001_initial.py
  students/sanghyun/users/migrations/__init__.py
  students/sanghyun/users/models.py
  students/sanghyun/users/tests.py
  students/sanghyun/users/views.py
  students/sanghyun/westagram/settings.py
Labels: 완료

#4 [김민지] Mission 2 : 모델링
  students/minji/requirements.txt
  students/minji/users/__init__.py
  students/minji/users/admin.py
  students/minji/users/apps.py
  students/minji/users/migrations/0001_initial.py
  students/minji/users/migrations/0002_alter_user_phonenumber.py
  students/minji/users/migrations/0003_user_created_at_user_updated_at_alter_user_email_and_more.py
  students/minji/users/migrations/__init__.py
  students/minji/users/models.py
  students/minji/users/tests.py
  students/minji/users/views.py
  students/minji/westargram/settings.py
Labels: 멘토 리뷰 요청

#9 [이원재] Mission 3 : 회원가입 기능 구현
  students/wonjae/users/urls.py
  students/wonjae/users/views.py
  students/wonjae/westagram/urls.py
Labels: 멘토 리뷰 요청

#10 [조예슬] Mission 3 : 회원가입 기능 구현
  students/yeseul/users/migrations/0001_initial.py
  students/yeseul/users/urls.py
  students/yeseul/users/views.py
  students/yeseul/westagram/urls.py
Labels: 멘토 리뷰 요청

#13 [안상현] Mission3 : 회원가입 기능 구현
  students/sanghyun/users/urls.py
  students/sanghyun/users/views.py
  students/sanghyun/westagram/urls.py
Labels: 멘토 리뷰 요청

#11 [이원재] Mission 4 : 로그인 기능 구현
  students/wonjae/users/urls.py
  students/wonjae/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 요청

#15 [김민지] Mission 3 : 회원가입 기능 구현
  students/minji/users/urls.py
  students/minji/users/views.py
  students/minji/westargram/urls.py
Labels: 멘토 리뷰 요청

#18 [안상현] Mission 4: 로그인 기능 구현
  students/sanghyun/users/urls.py
  students/sanghyun/users/views.py
Labels: 멘토 리뷰 요청

#14 [조예슬] Mission 4 : 로그인 기능 구현
  students/yeseul/users/urls.py
  students/yeseul/users/views.py
Labels: 멘토 리뷰 요청

#20 [조예슬] Mission 5: 회원가입 비밀번호 암호화 적용
  students/yeseul/users/views.py
Labels: 멘토 리뷰 요청

#21 [이원재] Mission 6 : 로그인 JWT 발급
  students/wonjae/users/views.py
Labels: 멘토 리뷰 요청

#22 [안상현] Mission 5: 회원가입 비밀번호 암호화 적용
  students/sanghyun/users/views.py
Labels: 멘토 리뷰 요청

#24 [김민지] Mission 5: 회원가입 비밀번호 암호화 적용
  students/minji/users/migrations/0004_rename_phonenumber_user_phone_number.py
  students/minji/users/models.py
  students/minji/users/views.py
Labels: 멘토 리뷰 요청

#23 [조예슬] Mission 6 : 로그인 JWT 발급
  students/yeseul/users/views.py
  students/yeseul/westagram/settings.py
Labels: 멘토 리뷰 요청

#26 [김민지] Mission 6: 로그인 JWT 발급
  students/minji/users/views.py
  students/minji/westargram/settings.py
Labels: 수정 요청

#25 [안상현] Mission 6: 로그인 JWT 발급
  students/sanghyun/users/views.py
Labels: 멘토 리뷰 요청
